### ISSUE TITLE
ejira does not appear to be published anywhere

### ISSUE THREAD

**Issue by zellio** [nyyManni/ejira#31]
Which repository is ejira published to for installation?

I cannot seem to find it in melpa, marmalade, or the gnu repositories.

**Comment by nyyManni** [comment]
Currently none, unfortunately.

There is an open issue about this already (#3), and the only thing blocking it is my lack of free time...

**Comment by zellio** [comment]
Sorry for the duplicate issue, I might have some time tonight to look at this if you are open to pull requests

**Comment by nyyManni** [comment]
I am more than happy to take in pull requests. All contributions are welcome
