### ISSUE TITLE
Working on issues with multiple users

### ISSUE THREAD

**Issue by robs-nice99** [nyyManni/ejira#32]
Hello,
I'm currently using org-jira and missing a feature that would allow to log time to issues where multiple users logged some time.

My question is, will ejira handle that correctly? Only updating my own times and also only counting my own time in "clocktabel"'s?

Thanks!

**Comment by nyyManni** [comment]
ejira has a one-way sync for time logging. This means that it is completely unaware of time that has been logged directly in JIRA. Depending on what is the functionality that you want this might be either correct or incorrect handling.

**Comment by robs-nice99** [comment]
Seems great. Will give it a try. Thanks!

**Comment by nyyManni** [comment]
Currently ejira does syncing per-day. So you first select a day you want to sync the hours from and then it syncs only hours recorded for that day (`M-x ejira-hourmarking-get-hourlog`).

The reason it is implemented this way is that it mirrored the workflow I had with syncing my effort for a given day at the end of that day. I am well aware that it definitely does not cover all the use cases, but currently I do not have enough free time to spend on features I do not personally use.

**Comment by robs-nice99** [comment]
Thanks for the clarification!
