### ISSUE TITLE
ejira-hourlog seems to be one hour off for every entry

### ISSUE THREAD

**Issue by beji** [nyyManni/ejira#33]
This project seems to be working really well for me but I run into a weird issue with the `ejira-hourmarking-get-hourlog` feature.
Clocking in and out of Tasks works really well and creates Logbook entries like this: 
```
CLOCK: [2020-10-27 Di 09:35]--[2020-10-27 Di 10:29] =>  0:54
CLOCK: [2020-10-27 Di 12:54]--[2020-10-27 Di 16:31] =>  3:37
```
But the hourlog turns this into something like this:
```
 09:35 |     -6m |      0m | XXX-XX          | XXX
 12:54 |  2h 37m |  2h 30m | XXX-XX          | XXX
```
Note the negative value here. It seems like every time value is one hour short and I have no idea how this happens (I assume that time zone related issues should affect both time strings equally). I'm not that well versed into Emacs debugging so I'm not sure how to start here.

Some infos about my system, maybe that helps?
- I'm running MacOs 10.15.7
- Emacs 27.1 from https://bitbucket.org/mituharu/emacs-mac/src/master/
- I use doom-emacs
`doom info` results in this:
```
SYSTEM  type       darwin
	config     x86_64-apple-darwin19.6.0
	shell      /bin/zsh
	uname      Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
	path       (~/.local/elixir-ls ~/.emacs.d/bin ~/.asdf/shims ~/.asdf/bin /usr/local/opt/m4/bin /usr/local/opt/node@12/bin ~/.oh-my-zsh/custom/plugins/git-open ~/.poetry/bin ~/.cargo/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Applications/VMware Fusion.app/Contents/Public /Library/Apple/usr/bin /usr/local/opt/fzf/bin /usr/local/Cellar/emacs-mac/emacs-27.1-mac-8.0/libexec/emacs/27.1/x86_64-apple-darwin19.6.0)
EMACS   dir        ~/.emacs.d/
	version    27.1
	build      Sep 30, 2020
	buildopts  --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-mac/emacs-27.1-mac-8.0/share/info/emacs --prefix=/usr/local/Cellar/emacs-mac/emacs-27.1-mac-8.0 --with-mac --enable-mac-app=/usr/local/Cellar/emacs-mac/emacs-27.1-mac-8.0 --with-gnutls --with-modules
	features   NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER GMP
	traits     (batch server-running envvar-file)
DOOM    dir        ~/.doom.d/
	version    2.0.9
	build      HEAD -> develop fe37a590c 2020-10-26 05:52:30 -0400
	elc-files  0
	modules    (:completion company (ivy +fuzzy) :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) snippets :emacs dired electric undo vc :term vterm :checkers syntax :tools debugger direnv docker (eval +overlay) lookup lsp magit terraform :os macos :lang data (elixir +lsp) emacs-lisp go (java +lsp) (javascript +lsp) markdown org sh web yaml :config (default +bindings +smartparens))
	packages   ((vcl-mode) (add-node-modules-path) (prettier-js) (fireplace) (lsp-treemacs) (ejira :recipe (:host github :repo nyyManni/ejira)))
	unpin      (n/a)
	elpa       (n/a)
```
I currently work around this by setting `ejira-hourmarking-step` to 60 and just increasing every entry one time.

**Comment by nyyManni** [comment]
Interesting. I copied your clock entries to one of my headings and it seems to work as expected.
```
 09:35 |     54m |  1h  0m | xxx     | xxx
 12:54 |  3h 37m |  3h 30m | xxx     | xxx
```
First thing that came to my mind would be the locale-specific settings. Would you be able to test with an english locale?

**Comment by beji** [comment]
I switched my sytem from german to english (which also updated the `locale` fields and the `current-language-environment` values) but it didn't change anything. This seems to indicate a bug in the emacs version, I'll try to get the "official" version going and see if that changes anything.

**Comment by nyyManni** [comment]
I am running from the master branch.

If you evaluate `(ejira-hourmarking--get-entries "2020-10-27")` and check the :start and :end -properties of one of the entries, and give those to `time-subtract` (like: `(time-subtract  '(24471 55884)  '(24471 52644))` ) does it give you a negative value?

**Comment by beji** [comment]
It actually doesn't. The log `[2020-10-27 Di 07:50]--[2020-10-27 Di 08:29] =>  0:39`  results in ` 07:50 |    -21m |    -15m ` and the following time entries: `(:start (24471 49944) :start-r (24471 49944) :end (24471 52284) :duration -1260 :duration-r -900)`. `(time-subtract '(24471 52284) '(24471 49944)) result in `2340`. Maybe they are used in the wrong order for some reason? `start-end` instead of `end-start`

**Comment by nyyManni** [comment]
Could you check what does `ejira-hourmarking-round` return for the following cases:
```lisp
(ejira-hourmarking-round '(24471 52284) 1)
(ejira-hourmarking-round '(24471 52284) 15)
```
For me I get:
```lisp
26940 (#o64474, #x693c)
27000 (#o64570, #x6978)
```

Trying to narrow down the location where the values go wild.

**Comment by beji** [comment]
I got 
```
23340 (#o55454, #x5b2c)
23400 (#o55550, #x5b68)
```

**Comment by beji** [comment]
I changed my system time zone which seems to affect the values here.
Using London gave me 
```
19740 (#o46434, #x4d1c)
19800 (#o46530, #x4d58)
```
Not sure if this helps

**Comment by nyyManni** [comment]
Found the issue:
```elisp
(defun ejira-hourmarking-round (time round-by)
  "Round TIME to nearest ROUND-BY."
  ;; Account for stupid time zone issues.
  (let* ((hours (- (string-to-number (format-time-string "%H" time)) 2))
         (minutes (string-to-number (format-time-string "%M" time)))
         (total (+ (* 60 hours) minutes))
         (rounded (round total round-by))
         (hours-r (/ rounded (/ 60 round-by)))
         (minutes-r (* round-by (% rounded (/ 60 round-by)))))
     (+ (* 3600 hours-r) (* 60 minutes-r))))
```


See the - 2 and the comment `;; Account for stupid time zone issues.`... Probably not the right place to fix it... Before I can come up with a proper fix adjusting that number 2 there is going to solve the issue for you 😄

**Comment by beji** [comment]
Yes, this does the trick. I changed it to a 1 and everything is correct now. Thank you for your time and help, I really appreciate it.

**Comment by DerBeutlin** [comment]
I experienced the same (also in the mid european time zone). 
For me the offset in ``ejira-hourmarking-round`` is 2 (probably because of daylight saving time? ) and hardcoding it to 1 fixed it.
